---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: ticket-api
  namespace: apps
  labels:
    area: tickets
    module: crm
spec:
  pathPrefix: "/tickets"
  service:
    name: ticket-app
    port:
      number: 3000
    openApiSpec:
      path: /openapi.yaml
      operationSets:
        - name: read
          matchers:
            - pathPrefix: /tickets
              methods:
                - GET
        - name: all-access
          matchers:
            - methods:
                - GET
                - POST
                - PUT
                # - DELETE
